# Generated by Django 5.1.1 on 2024-10-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price_usdt',
            field=models.PositiveIntegerField(),
        ),
    ]
