# Generated by Django 5.1.1 on 2024-11-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_currency_price_usdt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set(),
        ),
    ]
