networks:
  internal:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
  
  backend:
    image: backend-image
    container_name: backend
    env_file: .env
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - internal

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

volumes:
  postgres_data:
  static:
  media: