networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    networks:
      - internal
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - frontend
    volumes:
      - ./logs:/app/logs
      - static:/app/static
      - media:/app/media
    networks:
      - internal
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: worker
    entrypoint: celery
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./logs:/app/logs
      - media:/app/media
    depends_on:
      - redis
      - backend
    networks:
      - internal
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media
    networks:
      - internal

volumes:
  postgres_data:
  static:
  media: