version: '3.12'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: