networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal
  backend:
    image: backend-image
    container_name: backend
    env_file: .env
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - static:/app/static
      - media:/app/media
    networks:
      - internal
  worker:
    image: backend-image
    hostname: worker
    entrypoint: celery
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./logs:/app/logs
      - media:/app/media
    depends_on:
      - redis
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - static:/app/static
  #     - media:/app/media
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - internal

volumes:
  postgres_data:
  static:
  media: