# Generated by Django 5.1.1 on 2024-10-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_balance_crypto_user_balance_usdt_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
