# Generated by Django 5.1.1 on 2024-10-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance_crypto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance_usdt',
            field=models.IntegerField(),
        ),
    ]
