# Generated by Django 5.1.1 on 2024-10-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_balance_crypto_alter_user_balance_usdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance_crypto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance_usdt',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
